### PR TITLE
#64 - configurations for docker and nginx

### PR DESCRIPTION
**Pull request by kamilniemczycki**
Hello, it's me again.
I noticed that my previous change leads to problems when developing with containers. It doesn't break much, but also doesn't fix it. I'm sorry.

I'm sending patches that allow you to use the **"development"** and **"production"** modes - `MODE=development`. This can be set in the ***.env*** file.

I also gave a fifth point to the ***readme.md*** file.

### CODE REVIEW

**Comment by kamilpiech97** [comment]
Change PR title.

**Comment by kamilniemczycki** [comment]
@kamilpiech97, thank you for the information!

**Comment by mtracz** [comment]
We don't need this. For development we can just run `npm run serve` in node container, it will use built in server, and app will be on `localhost:8038` (DEVELOPMENT_NODE_PORT=8038).
Also I think that we don't need nginx at all, cause on dev we can ue node server, and on prod we will use github pages.

**Comment by kamilniemczycki** [comment]
There is a lot of truth in this. So, I'm closing.
Have a nice weekend!

**Pull request closed without merging**
